### ISSUE TITLE
Privacy issue

### ISSUE THREAD

**Issue by A-u-d** [lovasoa/resultats-concours-psi#1]
Bonjour,
Par curiosité j'ai recherché mon nom sur google et sur la première page de résultats je tombe sur le contenu de votre repository qui contient tous les résultats aux concours de psi. Je ne souhaite pas vous "report" dans la mesure du possible mais j'aimerais que quelque chose soit fait pour que ces résultats n'apparaissent plus ou ne soit au moins plus nominatifs car je pense que votre travail pose ici un problème de confidentialité...
Merci de votre compréhension.

**Comment by lovasoa** [comment]
Bonjour,
  Je comprends bien votre demande.
  J'ai supprimé tous les fichiers qui contenaient les noms des candidats.
  Veuillez m'excuser si la publication de vos résultats a pu vous causer du tord. 

Cordialement,
Ophir
